# Deploy BTP Infrastructure with Terraform using GitHub Actions.

name: 'BTP-TF-TRIAL-DESTROY'

on:
  # Allows you to run this workflow manually from the Actions tab.
  workflow_dispatch:

permissions:
  contents: read

jobs:
  BTP-TF-TRIAL:
    name: 'BTP-TF-TRIAL-DESTROY'
    runs-on: ubuntu-latest

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest.
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner.
    - name: Checkout Repo
      uses: actions/checkout@v3

    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token.
    - name: Intall Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{secrets.TF_API_TOKEN}}

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      run: terraform init

    # Checks that all Terraform configuration files adhere to a canonical format.
    - name: Terraform Format
      run: terraform fmt -check

    # Validate Terraform files.
    - name: Terraform Validate
      run: terraform validate

    # On manual start destroy all deployments.
    - name: Terraform Destroy 
      run: terraform destroy -auto-approve